services:
  app:
    environment:
      TZ: Europe/Zurich
    networks:
      - ehelvetica-test-webarchives
    volumes:
      - ./data/screenshots:/screenshots

  python:
    volumes:
      - ./data/thumbnails:/data/thumbnails

  nginx:
    networks:
      - ehelvetica-test-webarchives
      - ehelvetica-test-traefik
    volumes:
      - ./etc/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    links:
      - cantaloupe-webarchives

  cantaloupe-webarchives:
    build:
      context: ./.docker/cantaloupe
      dockerfile: Dockerfile
      args:
        TARGETPLATFORM: linux/arm64
    volumes:
      - ./data/cantaloupe:/var/lib/cantaloupe
      - ./data/collages:/var/lib/collages
      - ./data/cache/cantaloupe:/var/cache/cantaloupe
      - ./etc/cantaloupe/cantaloupe-dev.properties:/etc/cantaloupe.properties
    environment:
      - EHELVETICA_ACCESS_AUTHORIZE_URL=http://access.ehelvetica.localhost:8080/api/users/me
    networks:
      - ehelvetica-test-middleware
      - ehelvetica-test-traefik

networks:
  ehelvetica-test-middleware:
    external: true
  ehelvetica-test-webarchives:
    external: true
  ehelvetica-test-traefik:
    external: true
